name: 'Setup Sdkman'
author: 'Sergii Fesenko'
description: 'Manage dependencies with sdkman'
inputs:
  deps:
    required: true
    default: ''
    description: |
      space separated list of dependencies with optional version:
       dependency1[:version1] dependency2[:version2] ...
runs:
  using: "composite"
  steps:
    - id: hash
      run: |
        DEPS_HASH=`echo "${{ inputs.deps }}" | tr [:blank:] \\n | sort | xargs | md5sum | cut -f1 -d' '`
        echo "::set-output name=hash::${DEPS_HASH}"
      shell: bash
    - uses: actions/cache@v2
      with:
        path: ~/.sdkman/
        key: ${{ runner.os }}-${{ github.action }}-${{ steps.hash.outputs.hash }}
    - run: |
        if [ ! -s ~/.sdkman/bin/sdkman-init.sh ]; then
          curl -s "https://get.sdkman.io" | bash
          . ~/.sdkman/bin/sdkman-init.sh
          DEPS=`echo "${{ inputs.deps }}" | tr [:blank:] \\n | sort | xargs`
          for p in $DEPS; do
            pkg=(`echo $p | tr : ' '`)
            sdk install ${pkg[0]} ${pkg[1]}
          done
          sdk flush
        else
          . ~/.sdkman/bin/sdkman-init.sh
        fi
        echo $PATH | tr : \\n | grep .sdkman >> $GITHUB_PATH
      shell: bash