name: 'Setup '
author: 'Sergii Fesenko'
description: 'Manage dependencies with sdkman'
inputs:
  deps:
    required: true
    default: ''
    description: dependencies
runs:
  using: "composite"
  steps:
    - run: |
        hash=`echo "${{ inputs.deps }}" | tr [:blank:] \\n | sort | xargs | md5sum | cut -f1 -d' '`
        echo hash=$hash >> $GITHUB_ENV
      shell: bash
    - uses: actions/cache@v2
      with:
        path: ~/.sdkman/
        key: ${{ runner.os }}-${{ github.action }}-${{ env.hash }}
    - run: |
        if [ ! -s ~/.sdkman/bin/sdkman-init.sh ]; then
          curl -s "https://get.sdkman.io" | bash
          . ~/.sdkman/bin/sdkman-init.sh
          for p in "${{ inputs.deps }}"; do
            pkg=(`echo $p | tr : ' '`)
            sdk install ${pkg[0]} ${pkg[1]}
          done
          sdk flush
        else
          . ~/.sdkman/bin/sdkman-init.sh
        fi
        echo $PATH | tr : \\n | grep .sdkman >> $GITHUB_PATH
      shell: bash